config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/index'

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  get 'dashboard' => 'dashboard#index'
  

    root 'dashboard#index'

    resources :campaigns do
      resources :comments, module: :campaigns
    end

    resources :discussions do
      resources :comments, module: :discussions
    end
    
    resources :users

    resources :todo_lists
    
    resources :discussions

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  enum est_duration: [:week, :month, :three_month]
  has_many :todos
  has_many :discussions
  belongs_to :user
  has_many :comments, :as => :commentable
  has_many :taggings
  has_many :tags, through: :taggings

  accepts_nested_attributes_for :todos
  
  validates_presence_of :title, :purpose

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
        Tag.where(title: name.strip).first_or_create!
    end
  end
  
  def all_tags
    self.tags.map(&:title).join(", ")
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :commentable, :polymorphic => true
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
    belongs_to :campaign
    belongs_to :user
    has_many :comments, :as => :commentable
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :subtags, :class_name => "Tag", :foreign_key => "parent_id", :dependent => :destroy
  belongs_to :parent_tag, :class_name => "Tag"
  has_many :taggings
  has_many :campaigns, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :campaign
  belongs_to :tag
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :campaign 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum status: [:qualified, :not_qualified, :banned]

  has_many :campaigns
  
  has_many :discussions

  enum role: %w[Novice Expert]

  has_many :comments, class_name: "comment", foreign_key: "reference_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    
    
    dashboard_path # your path
  end

   private

  def user_not_authorized

    flash[:alert] = "Not authroized."
    redirect_to root_path
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def new
    @campaign = Campaign.new
    @campaign.todos.build
    authorize @campaign
  end

  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.user_id = current_user.id
    if @campaign.save
      flash[:success] = "Campaign successfully created"
      redirect_to root_path
    else
      flash[:notice] = "Something went wrong"
      render 'new'
    end
  end

  def show
    @campaign = Campaign.find(params[:id])
    @comments = @campaign.comments
    @comment = Comment.new
  end
  

  def campaign_params
    params.require(:campaign).permit(:title, :est_duration, :purpose,:all_tags, :todos_attributes => [:title])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = @commentable.comments.new comment_params
    @comment.user_id = current_user.id
    @comment.save
    redirect_to @commentable, notice: "Your comment was successfully posted."
  end

  private

  def comment_params
    params.require(:comment).permit(:title)
  end
    
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  def index
    @campaigns = Campaign.all
    @discussions = Discussion.all
  end

  def user_lists
    @users = User.where(role:'Novice')
    puts @users.inspect
  end

  def edit_user_status
    @user = User.find(params[:id])
  end

  def update_user_status
  end
  
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController

  before_action :check_campaign_exsists
  def new
    @discussion = Discussion.new
  end
  
  def create
		@discussion = Discussion.new(discussion_params)
		@discussion.user_id = current_user.id
    if @discussion.save
			flash[:success] = "Discussion Topic successfully created"
			redirect_to root_path
    else
			flash[:error] = "Something went wrong"
			render 'new'
    end
	end
	
	def show
		@discussion = Discussion.find(params[:id])
	end
	
  
  def check_campaign_exsists
    if !Campaign.first.present?
      flash[:error] = "Campaign dose not exsists"
      redirect_to root_path
    end
  end


  def discussion_params
    params.require(:discussion).permit(:title, :campaign_id)
	end
	
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController

	before_action :check_campaign_exsists
  def new
    @todo_list = Todo.new
  end

	def create
		@todo = Todo.new(params[:object])
		if @todo.save
			flash[:success] = "Object successfully created"
			redirect_to root_path
		else
			flash[:error] = "Something went wrong"
			render 'new'
		end
  end
  
  private

  def check_campaign_exsists
    if !Campaign.first.present?
      flash[:error] = "Campaign dose not exsists"
      redirect_to root_path
    end
  end

	def todo_params
    params.require(:todo).permit(:title,  :campaign_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.where(role:'Novice')
    authorize @users, :show_ideas?
    
  end

  def edit
    @user = User.find(params[:id])
  end
  

  def update
    @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        flash[:success] = "User was successfully updated"
        redirect_to users_path
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end
  
  def user_params
    params.require(:user).permit(:status)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns/comments_helper.rb
module Campaigns::CommentsHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/dashboard/edit_user_status.html.erb
<%= form_for :user, url: my_account_path(@user), action: :update, method: :post  do |f| %>
    <%= f.text_field :first_name %>
    <%= f.text_field :last_name %>
    <%= f.text_field :email %>
    <%= f.submit "Update Account" %>
<% end %>

app/views/dashboard/index.html.erb
<table class="table">
<h1>Campaign List</h1>
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Campaign Name</th>2
      <th scope="col">Action</th>2
    </tr>
  </thead>
  <tbody>
    <% @campaigns.each do |campaign| %>  
    <tr >
        <td><%= campaign.id%></td>
        <td><%= campaign.title %></td>
        <td><%= link_to 'VIEW', campaign %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<table class="table">
<h1>Discussion Topics</h1>
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Campaign Name</th>
      <th scope="col">Topic Name</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @discussions.each do |discussion| %>  
    <tr >
        <td><%= discussion.id%></td>
        <td><%= discussion.campaign.title %></td>
        <td><%= discussion.title %></td>

        <td><%= link_to 'VIEW', discussion %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard/user_lists.html.erb
<table class="table">
<h1>Campaign List</h1>
  <thead>
    <tr>
      <th scope="col">Username</th>
      <th scope="col">Email Address</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>  
    <tr >
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'VIEW', edit_user_path(id: user.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/todo_lists/new.html.erb
<%= form_for @todo_list, url: todo_lists_path(@todo_list) do |f| %>
  
  <div class="form-group">
     <%= f.label :campaign_id, 'Estimated Duration' %>
     <%= f.collection_select(:campaign_id, Campaign.all, :id, :title, {}, {:class=>'form-control'}) %>
  </div>
  
  
  <div class="form-group">
    <%= f.label :title, 'Todo Title' %>
    <%= f.text_field :title, class:'form-control' %>
  </div>'
    
  <%= f.submit  'Create Todo List', class:'btn btn-info btn-md' %>
<% end %>