config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/index'

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  get 'dashboard' => 'dashboard#index'
  

    root 'dashboard#index'

    resources :campaigns do
      resources :comments, module: :campaigns
    end

    resources :discussions do
      resources :comments, module: :discussions
    end
    
    resources :users

    resources :todo_lists
    
    resources :discussions

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  enum est_duration: [:week, :month, :three_month]
  has_many :todos
  has_many :discussions
  belongs_to :user
  has_many :comments, :as => :commentable
  has_many :taggings
  has_many :tags, through: :taggings

  accepts_nested_attributes_for :todos
  
  validates_presence_of :title, :purpose

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
        Tag.where(title: name.strip).first_or_create!
    end
  end
  
  def all_tags
    self.tags.map(&:title).join(", ")
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :commentable, :polymorphic => true
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
    belongs_to :campaign
    belongs_to :user
    has_many :comments, :as => :commentable
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :subtags, :class_name => "Tag", :foreign_key => "parent_id", :dependent => :destroy
  belongs_to :parent_tag, :class_name => "Tag"
  has_many :taggings
  has_many :campaigns, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :campaign
  belongs_to :tag
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :campaign 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum status: [:qualified, :not_qualified, :banned]

  has_many :campaigns
  
  has_many :discussions

  enum role: %w[Novice Expert]

  has_many :comments, class_name: "comment", foreign_key: "reference_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    
    
    dashboard_path # your path
  end

   private

  def user_not_authorized

    flash[:alert] = "Not authroized."
    redirect_to root_path
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def new
    @campaign = Campaign.new
    @campaign.todos.build
    authorize @campaign
  end

  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.user_id = current_user.id
    if @campaign.save
      flash[:success] = "Campaign successfully created"
      redirect_to root_path
    else
      flash[:notice] = "Something went wrong"
      render 'new'
    end
  end

  def show
    @campaign = Campaign.find(params[:id])
    @comments = @campaign.comments
    @comment = Comment.new
  end
  

  def campaign_params
    params.require(:campaign).permit(:title, :est_duration, :purpose,:all_tags, :todos_attributes => [:title])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = @commentable.comments.new comment_params
    @comment.user_id = current_user.id
    @comment.save
    redirect_to @commentable, notice: "Your comment was successfully posted."
  end

  private

  def comment_params
    params.require(:comment).permit(:title)
  end
    
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  def index
    @campaigns = Campaign.all
    @discussions = Discussion.all
  end

  def user_lists
    @users = User.where(role:'Novice')
    puts @users.inspect
  end

  def edit_user_status
    @user = User.find(params[:id])
  end

  def update_user_status
  end
  
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController

	before_action :check_campaign_exsists
  def new
    @todo_list = Todo.new
  end

	def create
		@todo = Todo.new(params[:object])
		if @todo.save
			flash[:success] = "Object successfully created"
			redirect_to root_path
		else
			flash[:error] = "Something went wrong"
			render 'new'
		end
  end
  
  private

  def check_campaign_exsists
    if !Campaign.first.present?
      flash[:error] = "Campaign dose not exsists"
      redirect_to root_path
    end
  end

	def todo_params
    params.require(:todo).permit(:title,  :campaign_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.where(role:'Novice')
    authorize @users, :show_ideas?
    
  end

  def edit
    @user = User.find(params[:id])
  end
  

  def update
    @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        flash[:success] = "User was successfully updated"
        redirect_to users_path
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end
  
  def user_params
    params.require(:user).permit(:status)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="/">The Idea App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if current_user.present?%>
        
         <li class="nav-item active">
            <%= link_to "Create Campaigns", new_campaign_path,  class:'nav-link' %>
        </li>

        <li class="nav-item active">
          <%= link_to "Create TODO List", new_todo_list_path,  class:'nav-link' %>
        </li>

        <li class="nav-item active">
          <%= link_to "Create Discussion Topics", new_discussion_path,  class:'nav-link' %>
        </li>

        <li class="nav-item active">
          <%= link_to "Novice Users", users_path,  class:'nav-link' %>
        </li>

        <li class="nav-item active">
            <%= link_to "Log out", destroy_user_session_path, method: "delete", class:'nav-link' %>
        </li>
        
        <% else %>
        <li class="nav-item active">
            <%= link_to "Log In", new_user_session_path,  class:'nav-link' %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestTask</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<%= render 'layouts/header' unless @disable_nav %>

<div class="container">
  <% flash.each do |type, msg| %>
    <div class="alert alert-info">
      <%= msg %>
    </div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>